apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-replication-controller

spec:
  replicas: 3
  selector:
    env: development
  template:
    metadata:
      name: testpod
      labels:
        env: development
    spec:
      containers:
        - name: c00
          image: ubuntu
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "while true; do echo Hello from Replication Controller; sleep 10; done"]
